# Generated by Django 6.0.7 on 2026-07-16 13:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(verbose_name="Место выполнения привычки")),
                ("action", models.CharField(verbose_name="Действие привычки")),
                (
                    "is_pleasant",
                    models.BooleanField(blank=True, default=False, verbose_name="Признак приятной привычки"),
                ),
                ("reward", models.CharField(blank=True, null=True, verbose_name="Вознаграждение")),
                (
                    "time_needed",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Продолжительность привычки не может быть меньше секунды."
                            ),
                            django.core.validators.MaxValueValidator(
                                120, message="Продолжительность привычки не может быть больше 120 секунд."
                            ),
                        ],
                        verbose_name="Время на выполнение привычки",
                    ),
                ),
                ("is_public", models.BooleanField(blank=True, default=False, verbose_name="Признак публичности")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="required_habits",
                        to="habits.habit",
                        verbose_name="Связанная приятная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["action", "is_public"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(verbose_name="Название")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("constant_interval", "Равные промежутки времени"),
                            ("times_in_week", "Несколько раз в неделю"),
                            ("times_in_month", "Несколько раз в месяц"),
                        ],
                        max_length=17,
                        verbose_name="Тип расписания",
                    ),
                ),
                (
                    "constant_interval",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Значение не может быть отрицательным"
                            ),
                            django.core.validators.MaxValueValidator(
                                10080, message="Значение не может быть больше 10080"
                            ),
                        ],
                        verbose_name="Постоянный интервал в минутах",
                    ),
                ),
                (
                    "times_in_week",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Список значений в минутах в течение недели"
                    ),
                ),
                (
                    "times_in_month",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Список значений в минутах в течение месяца"
                    ),
                ),
                (
                    "habit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="habits.habit",
                        verbose_name="Привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписания",
                "ordering": ["type"],
            },
        ),
    ]
